import "./globals.css"

import { Inter } from "next/font/google"
import LanguageSelector from "@/components/LanguageSelector"
import Link from "next/link"
import type { Metadata } from "next"
import ModelSelector from "@/components/ModelSelector"
import localFont from "next/font/local"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
})

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
})

const verdana = localFont({
  src: "./fonts/Verdana.woff",
  variable: "--font-verdana",
  weight: "100 900"
})

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${verdana.variable} ${inter.variable} flex min-h-screen flex-col gap-4 p-8 antialiased`}>
        <div className="flex flex-row justify-between">
          <div className="flex flex-row gap-4">
            <Link href="/">Home</Link>
            <Link href="/essays">Essays</Link>
          </div>
          <div className="flex flex-row gap-6">
            <ModelSelector />
            <LanguageSelector />
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
